### ISSUE TITLE
GetAlivePlayersOfSide null pointer

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/GRAD-On-The-Fly#4] opened 2023-11-26 20:35 UTC
null pointer to instance

maybe because of GM?!

```
Class:      'GRAD_OnTheFlyManager'
Entity id:2305843009213693953

Function: 'GetAlivePlayersOfSide'
Stack trace:
Scripts/Game/GameMode/OnTheFlyManager/GRAD_OnTheFlyManager.c:217 Function GetAlivePlayersOfSide
Scripts/Game/GameMode/OnTheFlyManager/GRAD_OnTheFlyManager.c:204 Function factionEliminated
Scripts/Game/GameMode/OnTheFlyManager/GRAD_OnTheFlyManager.c:139 Function CheckWinConditions
Scripts/Game/game.c:843 Function OnUpdate
21:41:37.183 RPL       (E): ReplicationError: Give called for identity which is not ready for replication! ident = 1
21:41:37.631 SCRIPT    (E): Virtual Machine Exception

Reason: NULL pointer to instance
```

**Comment by nomisum** [comment] 2023-11-26 20:51
might be fixed in https://github.com/gruppe-adler/GRAD-On-The-Fly/commit/619b1199b0b8b1ff3d2fb4c166fb778679fb04e2

**Comment by y0014984** [comment] 2023-11-27 15:56
Can't reproduce anymore. Seems to be fixed by various actions. Please double check.

**Closed** 2023-11-29 15:36 UTC
Labels: ready for test
